name: Regular report

on:
  workflow_dispatch:
#  schedule:
#    - cron: "35 16 * * *"
#    - cron: "25 4 * * *"
#    - cron: "5 10 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'

      - uses: actions/checkout@v2

      - name: Setup helium
        shell: pwsh
        run: |
          pip install helium

      - name: Auth
        shell: pwsh
        run: |
          python auth.py

      - name: Regular check report.
        env:
          IS_AT_SCHOOL: ${{ secrets.IS_AT_SCHOOL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        shell: pwsh
        run: |
          ./regular_check.ps1
